channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6.10
  - fastqc
  - sra-tools
  - snakemake-minimal
  - multiqc
  - bowtie2
  - samtools
  - htseq
  - graphviz
  - xorg-libxrender
  - xorg-libxpm
  - r-ggplot2
  - r-reshape2
  - r-pheatmap
  - bioconductor-rtracklayer
  - bioconductor-geoquery
  - r-rmarkdown
  - wget
