site_name: NBIS Reproducible research course
theme: mkdocs
pages:
  - Welcome: welcome.md
  - About: 'about.md'
  - 'The course':
    - Schedule: schedule.md
    - 'Travel info': travel.md
  - Tutorials:
    - 'Introduction to the tutorials': 'index.md'
    - Conda: 'conda.md'
    - Snakemake: 'snakemake.md'
    - Git: 'git.md'
    - R Markdown: 'rmarkdown.md'
    - Jupyter: 'jupyter.md'
    - Docker: 'docker.md'
    - 'Take down': take_down.md

markdown_extensions:
  - toc:
      permalink: 
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
extra_css: [extra.css]
