site_name: NBIS Reproducible research course
theme: mkdocs
pages:
  - 'index.md'
  - Tutorials:
    - 'Conda': 'conda.md'
    - 'Snakemake': 'snakemake.md'
    - 'Git': 'git.md'
    - 'Rmarkdown': 'rmarkdown.md'
    - 'Jupyter': 'jupyter.md'
    - 'Docker': 'docker.md'
