channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.10.10
  - fastqc=0.12.1
  - seqtk=1.3
  - snakemake=7.25.0
  - multiqc=1.14
  - bowtie2=2.5.1
  - tbb=2021.8.0
  - samtools=1.6
  - subread=2.0.3
  - bedtools=2.30.0
  - wget=1.20.3
  - graphviz=7.1.0
  - r-base=4.2.3
  - r-ggplot2=3.4.2
  - r-reshape2=1.4.4
  - r-stringi=1.7.12
  - r-pheatmap=1.0.12
  - r-rmarkdown=2.21
  - r-r.utils=2.12.2
  - bioconductor-rtracklayer=1.30.1
  - bioconductor-geoquery=2.66.0
  - xorg-libxrender
  - xorg-libxpm
