name: rmarkdown-env
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base
  - r-ggplot2
  - r-reshape2
  - r-stringi
  - r-pheatmap
  - r-rmarkdown
  - r-r.utils
  - bioconductor-geoquery
  - r-devtools
  - r-networkd3
  - rstudio
