name: jupyter-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - biopython
  - jupyter
  - pandas
  - seaborn
  - matplotlib
  - ipywidgets
  - nbconvert
  - jinja2<
  - jupyter_contrib_nbextensions