name: snakemake-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.9
  - fastqc=0.12.1
  - seqtk=1.3
  - snakemake=7.24.0
  - multiqc=1.14
  - bowtie2=2.5.1
  - tbb=2021.8.0
  - samtools=1.16.1
  - subread=2.0.3
  - graphviz=7.0.5
  - wget=1.20.3
  - xorg-libxrender
  - xorg-libxpm
