name: git-env
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python=3.10.9
  - fastqc=0.12.1
  - seqtk=1.3
  - snakemake=7.24.0
  - multiqc=1.14
  - bowtie2=2.5.1
  - tbb=2021.8.0
  - samtools=1.16.1
  - subread=2.0.3
  - bedtools2.30.0
  - wget=1.20.3
  - graphviz=7.0.5
  - r-base=4.1.3
  - r-ggplot2=3.3.5
  - r-reshape2=1.4.4
  - r-stringi=1.7.6
  - r-pheatmap=1.0.12
  - r-rmarkdown=2.13
  - r-r.utils=2.11.0
  - bioconductor-rtracklayer=1.54.0
  - bioconductor-geoquery=2.62.0
  - xorg-libxrender
  - xorg-libxpm
