name: lecture-env
channels:
    - conda-forge
    - bioconda
dependencies:
    # Snakemake
    - snakemake-minimal
    # R
    - r-base
    - r-ggplot2
    - r-kableextra
    - r-palmerpenguins
    - r-stringi
    - r-tidyr
