name: lecture-env
channels:
    - conda-forge
    - bioconda
dependencies:

    # Snakemake
    - snakemake-minimal

    # Jupyter
    - python
    - jupyter
    - pandas
    - jupyter_contrib_nbextensions
    - nbconvert
    - seaborn
    - rpy2
    - pyppeteer
    - jinja2

    # R and Xaringan
    - phantomjs
    - r-base
    - r-ggplot2
    - r-kableextra
    - r-palmerpenguins
    - r-stringi
    - r-tidyr
    - r-xaringan
    - r-webshot
    - pip
    - pip:
          - RISE
