name: lectures

channels:
    - conda-forge
    - defaults
    - r

dependencies:
  - python=3.8.2
  - jupyter=1.0.0
  - pandas=1.0.2
  - rise=5.6.1
  - seaborn=0.10.0
  - rpy2=3.1.0
  #  Base R
  - r-base=3.6.2
  # Xaringan (for creating presentations)
  - r-xaringan=0.15
  - r-ggplot2=3.3.0
