name: nextflow-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.4.4
  - fastqc=0.11.9
  - multiqc=1.10.1
  - nextflow=21.04.0
  - samtools=1.12
  - sra-tools=2.10.1
  - subread=2.0.1
  - wget=1.20.1
