channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - r-base=3.6.2
  - rstudio=1.1.456
  - r-ggplot2=3.2.1
  - r-networkd3=0.4
  - r-pheatmap=1.0.12
  - r-reshape2=1.4.3
  - r-rmarkdown=2.1
  - bioconductor-rtracklayer=1.46.0
  - bioconductor-geoquery=2.54.0
