name: jupyter-env
channels:
  - conda-forge
  - bioconda
  - main
dependencies:
  - python=3.7.6

  # Workflow dependencies
  - fastqc=0.11.9
  - sra-tools=2.10.1
  - snakemake-minimal=5.10.0
  - multiqc=1.7
  - bowtie2=2.3.5.1
  - tbb=2020.3
  - samtools=1.10
  - htseq=0.11.2
  - bedtools=2.29.2
  - wget=1.20.1
  - graphviz=2.42.3

  # Notebook dependencies for tutorial
  - biopython=1.78
  - jupyter=1.0.0
  - pandas=1.2.3
  - seaborn=0.11.1
  - matplotlib=3.3.4
  - ipywidgets=7.6.3
  - nbconvert=5.6.1
  - jupyter_contrib_nbextensions=0.5.1





