channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6.10
  - fastqc=0.11.9
  - sra-tools=2.10.0
  - snakemake-minimal=5.10.0
  - multiqc=1.7
  - bowtie2=2.3.5.1
  - samtools=1.10
  - htseq=0.11.2
  - bedtools=2.29.2
  - wget=1.20.1
  - graphviz=2.40.1