name: slim-setup

on:
  workflow_dispatch:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main

jobs:
  docker-slim-install:
    # Install environments inside the slim container
    runs-on: ubuntu-latest
    container:
      nbisweden/workshop-reproducible-research:slim
    strategy:
      matrix:
        env: [ snakemake, nextflow, jupyter, rmarkdown ]
        include:
          - env: snakemake
            cmd: snakemake -c 1 -d tutorials/snakemake/ -s tutorials/snakemake/snakefile_mrsa.smk
          - env: nextflow
            cmd: cd tutorials/nextflow && nextflow run main_mrsa.nf
          - env: jupyter
            cmd: jupyter nbconvert --to HTML tutorials/jupyter/supplementary_material.ipynb
          - env: rmarkdown
            cmd: mamba install --force-reinstall -y pandoc && cd tutorials/rmarkdown && echo 'rmarkdown::render("code/supplementary_material.Rmd", output_file="supplementary.html")' | R --vanilla
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.env }}
        shell: bash -l {0}
        run: |
          mamba env create -f tutorials/${{ matrix.env }}/environment.yml
          conda activate ${{ matrix.env }}-env
          ${{ matrix.cmd }}
