name: MRSA container testing

on:
  workflow_dispatch:
    branches:
      - main
      - devel
  pull_request:
    paths:
      - 'tutorials/containers/Dockerfile'
      - 'tutorials/containers/environment.yml'
      - 'tutorials/containers/Snakefile'
      - 'tutorials/containers/config.yml'
      - 'tutorials/containers/code/*'
    branches:
      - main

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test Docker image
        run: |
          docker build -t my_docker_project -f tutorials/containers/Dockerfile tutorials/containers/
          docker run --rm my_docker_project
