name: slim-setup

on:
  workflow_dispatch:
    branches:
      - main
      - devel
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-slim-install:
    # Install environments inside the slim container
    runs-on: ubuntu-latest
    container:
      nbisweden/workshop-reproducible-research:slim
    strategy:
      matrix:
        env: [ snakemake, jupyter, rmarkdown ]
        include:
          - env: snakemake
            cmd: conda install -y -c bioconda multiqc=1.7 bowtie2=2.3.5.1 samtools=1.10 htseq=0.11.2 && snakemake -j 1 -d tutorials/snakemake/ -s tutorials/snakemake/snakefile_mrsa.smk
          - env: jupyter
            cmd: jupyter nbconvert --template=nbextensions --to HTML tutorials/jupyter/supplementary_material.ipynb
          - env: rmarkdown
            cmd: echo 'rmarkdown::render("tutorials/rmarkdown/code/supplementary_material.Rmd", output_file="supplementary.html")' | R --vanilla
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
          activate-environment: ${{ matrix.env }}-env
          environment-file: tutorials/${{ matrix.env }}/environment.yml
          auto-activate-base: false
      - name: Test ${{ matrix.env }}
        shell: bash -l {0}
        run: |
          conda list
          ${{ matrix.cmd }}