name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-and-run:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Docker build
          run: |
            docker build -t my_docker_project -f docker/Dockerfile docker/
            docker run --rm my_docker_project