name: slim-setup

on:
  workflow_dispatch:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main

jobs:
  docker-slim-install:
    # Install environments inside the slim container
    runs-on: ubuntu-latest
    container:
      nbisweden/workshop-reproducible-research:slim
    strategy:
      matrix:
        env: [ snakemake, nextflow, jupyter, rmarkdown ]
        include:
          - env: snakemake
            cmd: snakemake -c 1 -d tutorials/snakemake/ -s tutorials/snakemake/snakefile_mrsa.smk
          - env: nextflow
            cmd: cd tutorials/nextflow && nextflow run main_mrsa.nf
          - env: jupyter
            cmd: jupyter nbconvert --to HTML tutorials/jupyter/supplementary_material.ipynb
          - env: rmarkdown
            cmd: mamba install --force-reinstall -y r-stringi && cd tutorials/rmarkdown && echo 'rmarkdown::render("code/supplementary_material.Rmd", output_file="supplementary.html")' | R --vanilla
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: ${{ matrix.env }}-env
          environment-file: tutorials/${{ matrix.env }}/environment.yml
          use-mamba: true
      - name: Test ${{ matrix.env }}
        shell: bash -l {0}
        run: |
          conda list
          ${{ matrix.cmd }}
