name: lectures

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the main branch
on:
  push:
    paths:
      - 'lectures/*/*.Rmd'
      - 'lectures/*/*.ipynb'
      - '.github/workflows/lectures.yml'
  pull_request:
    paths:
      - 'lectures/*/*.Rmd'
      - 'lectures/*/*.ipynb'
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: lecture-env
        environment-file: lectures/environment.yml
        use-mamba: true
    - name: Render lectures
      run: |
        snakemake -d lectures/ -s lectures/Snakefile -c 1