name: lectures

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the main branch
on:
  push:
    paths:
      - 'lectures/*/*.Rmd'
      - 'lectures/*/*.ipynb'
      - '.github/workflows/*.yml'
    branches:
      - lectures
      - main
  pull_request:
    paths:
      - 'lectures/*/*.Rmd'
      - 'lectures/*/*.ipynb'
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install the conda environment
      run: conda env update -n base -f lectures/environment.yml
    - name: Render lectures
      run: snakemake -d lectures/ -s lectures/Snakefile -j 1
    - name: Upload lectures
      uses: actions/upload-artifact@v2
      with:
        name: lectures
        path: lectures/*/*.html
