name: Render and publish site

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - specky

jobs:
  publish:
    runs-on: ubuntu-latest
    container: ghcr.io/nbisweden/workshop-reproducible-research/publish:specky
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
